# Generated by Django 5.1.6 on 2025-02-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_footercontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterContent',
        ),
    ]
