# Generated by Django 5.1.6 on 2025-02-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'İletişim Mesajı', 'verbose_name_plural': 'İletişim Mesajları'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='İstanbul, Türkiye', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='location',
            field=models.CharField(default='İstanbul, Türkiye', help_text='Örn: İstanbul, Türkiye', max_length=200),
            preserve_default=False,
        ),
    ]
