# Generated by Django 5.1.6 on 2025-02-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_contact_options_rename_name_contact_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon', models.CharField(help_text='Font Awesome class name (örn: fab fa-github)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='social_media',
            field=models.ManyToManyField(blank=True, to='main.socialmedia'),
        ),
    ]
