# Generated by Django 5.1.6 on 2025-02-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_socialmedia_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
